version: '2.2'

services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000" 
    environment:
      MYSQL_HOST: mysql  
      MYSQL_PORT: 3306  
      MYSQL_USER: archit  
      MYSQL_PASSWORD: admin123 
      MYSQL_DATABASE: qp_assesement  
    volumes:
      - ./:/usr/src/app  
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123 
      MYSQL_DATABASE: qp_assesement
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
