version: '2.2'

services:
  nestjs_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000" 
    environment:
      - PORT= 3000 
    volumes:
      - ./:/usr/src/app  
    depends_on:
      - mysql_db_test

  mysql_db_test: 
    image: mysql
    ports: 
     - "3308:3308"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=qp_assesement
     - MYSQL_USER=testuser
     - MYSQL_PASSWORD=testuser
     - MYSQL_PORT=3308