version: '2.2'

services:
  nestjs_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000" 
    environment:
      - PORT= 3000
      # MYSQL_HOST: mysql  
      # MYSQL_PORT: 3307  
      # MYSQL_USER: root  
      # MYSQL_PASSWORD: admin123 
      # MYSQL_DATABASE: qp_assesement  
    volumes:
      - ./:/usr/src/app  
    # depends_on:
    #   - mysql

  mysql_db_test: 
    image: mysql
    ports: 
     - "3308:3308"
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=qp_assesement
     - MYSQL_USER=testuser
     - MYSQL_PASSWORD=testuser
     - MYSQL_PORT=3308




#   mysql:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: admin123 
#       MYSQL_DATABASE: qp_assesement
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:
